import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={styles.main}>
        <h1 className={styles.title}>
          &lt;Hunting Coder/&gt;
        </h1>
        <p className={styles.description}>
          A Blog For Hunting Coders By Hunting Coder
        </p>
        <div className="blogs">
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div >
            <h3  className={styles.h3}>How To Learn Javascript In 2022?</h3>
            <p className={styles.p}>Javascript is  a language used to describe logic for web</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div >
            <h3 className={styles.h3}>How To Learn Javascript In 2022?</h3>
            <p>Javascript is  a language used to describe logic for web</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div >
            <h3 className={styles.h3}>How To Learn Javascript In 2022?</h3>
            <p>Javascript is  a language used to describe logic for web</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
